/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktdrive

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
  @Test fun testAppHasAGreeting() {
    val classUnderTest = KtDrive()
    assertNotNull(classUnderTest.SCOPES, "app should have auth scopes")
  }
}

// vim: se et ts=2 sw=2 number:
